### ISSUE TITLE
May I ask LayoutFormer++ and LayoutDiffusion which works better? and their difference in application？

### ISSUE THREAD

**Issue by hangzeli08** [microsoft/LayoutGeneration#22]
I know they're all good, which one is better, and what's the difference between the various applicability scenarios？

**Comment by Junyi42** [comment]
Hi @hangzeli08,

Thank you for your interest in our research. To provide a clearer understanding, here's a comparison of LayoutDiffusion and LayoutFormer++ based on some of their strengths and limitations:

**LayoutDiffusion Advantages:**

1. **Diversity:** It generates more diverse layouts than LayoutFormer++ with comparable quality.
2. **Adaptability:** Even though it's trained solely on unconditional generation, LayoutDiffusion can perform certain conditional tasks like Gen-Type and refinement without additional training.

**LayoutDiffusion Disadvantages:**

1. **Speed:** LayoutDiffusion is much slower, requiring 200 steps for one generation, compared to LayoutFormer++.
2. **Task Range:** LayoutFormer++ has a broader multitasking capability and can handle additional tasks that LayoutDiffusion can't, such as Gen-Relationship.

For a comprehensive understanding, I recommend checking out the respective papers.

Warm regards,
Junyi
