### ISSUE TITLE
LayoutPrompter link not working

### ISSUE THREAD

**Issue by drchrisscheier** [microsoft/LayoutGeneration#31]
Thank you for the exciting paper on LayoutPrompter, really interesting!

i tried to access the link given in this repo but it does not work (neither does the link given in the arvix paper version https://arxiv.org/abs/2311.06495). 

thank you!

**Comment by Usernamezhx** [comment]
+1

**Comment by Usernamezhx** [comment]
now. it is working.

**Comment by ShizhaoSun** [comment]
It works now. Try it again!

**Comment by ShizhaoSun** [comment]
We just released the code. Try it now :)
