### ISSUE TITLE
LayoutPrompter evaluation code?

### ISSUE THREAD

**Issue by conan1024hao** [microsoft/LayoutGeneration#35]
Hi, thank you for sharing LayoutPrompter's code! It's really an amazing work.

Do you have a plan to public the evaluation part code or share some implementation details? Such as do you only use the top result for calculate alignment, overlap... or average the 10 output results?

**Comment by kaoshizhou** [comment]
Thanks for paying attention to our work! In the experimental results except Table 8, we calculate metrics on the top-1 layouts of the layout ranker. In Table 8, we use all 10 outputs to calculate the means and variances of the metrics to show the stability of the performance.

We use the evaluation code of baseline works for fair comparison. Specifically, 
1. for constraint-explicit layout generation, the evaluation code is [here](https://github.com/microsoft/LayoutGeneration/blob/main/LayoutFormer%2B%2B/src/evaluation/metrics.py).
2. for content-aware layout generation, the evaluation code is [here](https://github.com/PKU-ICST-MIPL/PosterLayout-CVPR2023/blob/main/eval.py).
3. for text-to-layout, the evaluation code is [here](https://github.com/microsoft/LayoutGeneration/blob/main/Parse-Then-Place/src/evaluation/metrics.py).
